### ISSUE TITLE
Failed to run tests

### ISSUE THREAD

**Issue by segrey** [shrynx/react-super-scripts#15]
### Can you reproduce the problem with latest npm?

>```
>npm install -g npm@latest
>
>cd your_project_directory
>rm -rf node_modules
>npm install
>```

Done, the problem can still be reproduced (npm@5.3.0).

### Description

1. npm install -g create-react-app
2. create-react-app my-app --scripts-version react-super-scripts
3. Running `npm test` fails with
```
 FAIL  src/App.test.js
  ● Test suite failed to run

    Cannot find module 'src/App' from 'App.test.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at Object.<anonymous> (src/App.test.js:3:38)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.734s
Ran all test suites.
```

### Expected behavior

`src/App` should be found from App.test.js and tests should be passed

### Actual behavior

```
Test suite failed to run

    Cannot find module 'src/App' from 'App.test.js'
```

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls react-scripts` (if you haven’t ejected): 
```
~/temp/my-app6 $ npm ls react-scripts
my-app6@0.1.0 /home/segrey/temp/my-app6
└── (empty)

~/temp/my-app6 $ npm ls react-super-scripts
my-app6@0.1.0 /home/segrey/temp/my-app6
└── react-super-scripts@0.2.4 
```
2. `node -v`: 
v8.2.0
3. `npm -v`:
5.3.0

Operating system: Linux 3.19.0-32-generic 37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Browser and version:
No browser involved here

### Reproducible Demo

It can be reproduced on a freshly generated app.

**Comment by segrey** [comment]
Not reproduced anymore
